

```{r setup-7, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# شخصية الملك عبد العزيز{-}

لقد كان الملك عبدالعزيز وحيد زمانه فيما اتصف به من مقومات شخصية فذة، ويمكن إيجاز صفاته ومناقبه فيما يلي:

-
كان مؤمناً عميق الإيمان، يعتمد على الله تعالى في كل أمر من أموره، ولا يسأل سواه فيما يتطلع إليه.

-
كان يملك خبرة وا​سعة بشؤون دينه، فقد حفظ القرآن الكريم وكثيراً من الأحاديث النبوية الشريفة، وألم إلماماً واسعاً بالأحكام الشرعية ووضعها موضع التطبيق فيما أولاه الله من السلطان، وظل طوال حياته يجتمع كل ليلة مع العلماء والفقهاء حيث تُقرأ كتب العلوم الدينية ويدور الحديث حولها بينه وبين جلسائه.

-
كان حكيماً يُعمل عقله في كل حركة من حركاته، ولكل خطوة عنده حساب دقيق، يقلب الأمور على وجوهها ثم يختار الطريق الذي يراه أفضل الطرق، ويكون اختياره في الأغلب هو الاختيار الصحيح.

-
كان شجاعاً إلى درجة كبيرة، فلا يتردد في خوض المعارك إذا اضطر لها مهما كانت قوة خصمه وعدده وعدته.

كان قائداً عسكرياً موهوباً يجيد رسم الخطط الحربية وتنفيذها، وكثيراً ما استعاد وقائع معركة جرت وتحقق له الانتصار فيها ليبين أخطاء خصمه وما كان يجب أن يفعل لينتصر عليه.

-
كان خبيراً بالمجتمعات البدوية والحضرية في شبه الجزيرة العربية، وعلى خبرة واسعة بالقبائل وأنسابها بحيث يعرف قبيلة مخاطبه من أول جملة ينطق بها، ومن موقع هذه الخبرة كان يتعامل مع الناس حسب المجتمع الذي ينتسبون إليه بدوياً كان أم حضرياً.

-
كان شديد التمسك بأحكام الدين، فلا يتهاون إزاءها ولا يهادن، و فيما عدا ذلك كان رقيق القلب مرهف الإحساس.

-
كان اهتمامه يشمل الجميع، والناس أمامه سواسية حتى يبلغ الحق مستقره.


